- name: Starting all tasks
  hosts: all
  become: no
  gather_facts: false 

  roles:
     - linux_ip_forward
     - install_base_docker
     - docker_grafana
     - linux_ns_simple_net
     - linux_hardening_disable_ctrl_alt_del
     - docker_mtproto_proxy
     - linux_hardening_pam_pwq_pwh
     - linux_hardening_pam_faillock