---
- name: Send password policy configuration template ({{ ansible_distribution }})
  ansible.builtin.template:
    src: pwquality.conf.j2
    dest: "{{ pw_default_dir }}{{ pw_pwq_f }}"
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Send password history configuration template
  ansible.builtin.template:
    src: pwhistory.conf.j2
    dest: "{{ pw_pwh_dir }}{{ pw_pwh_f }}"
    owner: root
    group: root
    mode: '0644'

- name: Send {{ ansible_distribution }} PAM "{{ pam_common_password }}"
  ansible.builtin.template:
    src: deb_pam_common-password.j2
    dest: "{{ pw_default_pam_dir }}{{ pam_common_password }}"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Send password policy configuration template (RedHat)
  ansible.builtin.template:
    src: pwquality.conf.j2
    dest: "{{ pw_default_rhel_dir }}{{ pw_pwq_f }}"
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "RedHat"