---
docker_repo_url: "https://download.docker.com/linux/rhel/$releasever/$basearch/stable"
docker_repo_name: "docker-ce"
docker_repo_gpgkey: "https://download.docker.com/linux/rhel/gpg"
docker_repo_description: "Docker CE Repository"
docker_packages:
   - docker-ce
   - docker-ce-cli
   - containerd.io
   - docker-compose-plugin
   - docker-buildx-plugin
   - git