---
- name: Install auditd packages ({{ ansible_distribution }})
  ansible.builtin.package:
    name: "{{ auditd_packages }}"
    state: present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"